# shared by colcon_package.rb and colcon_import_package.rb

require 'json'

# hackily reopen and extend the ImporterPackage class to store cmake args for a colcon.pkg file
module Autobuild
    class ImporterPackage
        attr_accessor :optional_deps

        #re-implement the original initialize of ImporterPackage + init @colcon_pkg
        def initialize(*args)
            @exclude = []
            @colcon_pkg = Hash.new
            @optional_deps = Array.new
            super
        end

        # function to add a cmake arg
        def add_cmake_arg(value)
            (@colcon_pkg["cmake-args"] ||= Array.new).push(value)
        end

        # function to add optional dependencies form the mainifest.xml to the package.xml
        def use_optional_dependency(value)
            @optional_deps.push(value)
        end

        # parse/append/write colcon.pkg file if cmake-args were added via add_cmake_arg()
        def write_colcon_pkg_file()
            # the cmake-args key is only present if add_cmake_arg was called
            if @colcon_pkg.has_key?("cmake-args") then
                output = Hash.new
                if File.exist?(srcdir + "/colcon.pkg") then
                    File.open(srcdir + "/colcon.pkg") do |file|
                        #load output with existing file to keep all values
                        output = JSON.load(file)
                    end
                end
                # merge new cmake-args to output
                # if !output.has_key?("cmake-args") then
                #     # add key
                #     output["cmake-args"] = Array.new
                # end
                # output["cmake-args"] |= @colcon_pkg["cmake-args"]

                # overwrite cmake-args, as those which were added by call to pkg.add_cmake_arg() have to be removed from the file
                # (re-loaded) by parsing the file
                output["_comment"] = "cmake-args are autogenerated, they will be overwritten on next autoproj update, change them in your overrides.rb"
                output["cmake-args"] = @colcon_pkg["cmake-args"]
                File.write(srcdir + "/colcon.pkg", JSON.pretty_generate(output))
            end
        end
    end
end

# register the post_install hook that hands the actual build over to colcon
def colcon_build_hook(pkg, workspace)
    pkg.post_install do |pkg|
        colcon_dir = File.expand_path(workspace.root_dir + "/../")
        cmd = ['colcon', 'build']
        if (Autoproj.config.get("COLCON_USE_SYMLINK_INSTALL") == true) then
            cmd << '--symlink-install'
        end
        cmd += ['--event-handlers', 'console_direct+', '--packages-select', pkg.name]

        pkg.progress_start "building %s using colcon in #{colcon_dir}" do
            Autobuild::Subprocess.run(pkg, 'build', *cmd, :working_directory => colcon_dir)
        end
    end
end
